package myclassproject.mystorygraph;

//Fill this enum with the labels you chose for the NODES of your story graph.
public enum MyNodeLabels{
	root, //other nodes
	KnockOnDoor,
	OutsideManor,
	LookinBushesA,
	UnderDoormatA,
	UnderDoormatB,
	LookInBushesB,
	EnterManor,
	MasterBedroomA,
	MasterBedroomB,
	WifeAlibi1A,
	WifeAlibi2A,
	WifeAlibi1B,
	WifeAlibi2B,
	PinkGlitter1A,
	PinkGlitter2A,
	PinkGlitter1B,
	PinkGlitter2B,
	LaundryRoomA,
	LaundryRoomB,
	MaidAlibi1A,
	MaidAlibi2A,
	MaidAlibi1B,
	MaidAlibi2B,
	BloodyRags1A,
	BloodyRags2A,
	BloodyRags1B,
	BloodyRags2B,
	ReturnToManorA,
	ReturnToManorB,
	KitchenA,
	KitchenB,
	ChefAlibiA,
	ChefAlibiB,
	EatChickenA,
	EatChickenB,
	BadEndingA,
	BadEnding1B,
	BadEnding2B,
	FindSkull,
	ArrestChef,
	BelieveChef,
	GoodEnding,
	
}
